[package]
name = "libradon"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
linked_list_allocator = "0.10.5"
log = "0.4.29"
radon_kernel = { path = "../kernel" }
spin = "0.10.0"

[lib]
crate-type = ["rlib"]
